"""The Tiny radio launcher icon, defined once and written out as Android vector drawables (and SVG for previews).

Regenerate after editing:
    python3 tools/launcher_icon.py foreground peas > app/src/main/res/drawable/ic_launcher_foreground.xml
    python3 tools/launcher_icon.py monochrome > app/src/main/res/drawable/ic_launcher_monochrome.xml
The background colour is in app/src/main/res/values/ic_launcher_background.xml.
"""
import sys

# Geometry on the 108-unit adaptive icon canvas (safe zone: circle of radius 33 around 54,54).
ANTENNA = ((70, 41), (79, 26), 3.0)
ANTENNA_KNOB = (79, 26, 2.8)
BODY = (27, 41, 54, 36, 8)  # x, y, w, h, corner radius
PANEL = (30.5, 45, 29, 29, 4)
DOTS = [(x, y, 2.1) for y in (49, 56, 63, 70) for x in (35, 42, 49, 56)]
DIAL = (70, 54, 6, 2.6)  # cx, cy, r, stroke width
POINTER = ((70, 54), (73.5, 50.5), 2.2)
KNOB = (70, 69, 2.8)

PEA_DARK, POD, POD_SHADE, PEA = "#1f4a35", "#8fd16a", "#4f9a3b", "#d9f5b5"
VARIANTS = {
    # name: background, body/antenna, panel (None = no panel), grille dots, dial and knob
    "peas": ("Peas in the speaker", PEA_DARK, POD, POD_SHADE, PEA, PEA_DARK),
    "pea": ("Pea radio", PEA_DARK, PEA, None, PEA_DARK, PEA_DARK),
    "pod": ("Pod radio", PEA_DARK, POD, None, PEA_DARK, PEA_DARK),
    "light": ("Light pod", PEA, PEA_DARK, None, POD, POD),
}


def f(n):
    return f"{n:g}"


def circle(cx, cy, r):
    return f"M{f(cx - r)},{f(cy)}a{f(r)},{f(r)} 0 1,0 {f(2 * r)},0a{f(r)},{f(r)} 0 1,0 {f(-2 * r)},0z"


def rrect(x, y, w, h, rx):
    return (f"M{f(x + rx)},{f(y)}h{f(w - 2 * rx)}a{f(rx)},{f(rx)} 0 0 1 {f(rx)},{f(rx)}v{f(h - 2 * rx)}"
            f"a{f(rx)},{f(rx)} 0 0 1 {f(-rx)},{f(rx)}h{f(-(w - 2 * rx))}a{f(rx)},{f(rx)} 0 0 1 {f(-rx)},{f(-rx)}"
            f"v{f(-(h - 2 * rx))}a{f(rx)},{f(rx)} 0 0 1 {f(rx)},{f(-rx)}z")


def line(a, b):
    return f"M{f(a[0])},{f(a[1])}L{f(b[0])},{f(b[1])}"


def layers(variant):
    """(path data, fill or None, stroke or None, stroke width, even-odd) for the full-colour foreground."""
    _, _, body, panel, dots, dial = VARIANTS[variant]
    out = [
        (line(*ANTENNA[:2]), None, body, ANTENNA[2], False),
        (circle(*ANTENNA_KNOB), body, None, 0, False),
        (rrect(*BODY), body, None, 0, False),
    ]
    if panel:
        out.append((rrect(*PANEL), panel, None, 0, False))
    out += [
        ("".join(circle(*d) for d in DOTS), dots, None, 0, False),
        (circle(*DIAL[:3]), None, dial, DIAL[3], False),
        (line(*POINTER[:2]), None, dial, POINTER[2], False),
        (circle(*KNOB), dial, None, 0, False),
    ]
    return out


def mono_layers():
    """Single-colour version for Android's themed icons: the grille, dial and knob are cut out of the body."""
    cx, cy, r, w = DIAL
    body = rrect(*BODY) + "".join(circle(*d) for d in DOTS) + circle(cx, cy, r + w / 2) + circle(cx, cy, r - w / 2) + circle(*KNOB)
    return [
        (line(*ANTENNA[:2]), None, "#000000", ANTENNA[2], False),
        (circle(*ANTENNA_KNOB), "#000000", None, 0, False),
        (body, "#000000", None, 0, True),
    ]


def vector_xml(ls):
    paths = []
    for d, fill, stroke, width, evenodd in ls:
        attrs = [f'android:pathData="{d}"']
        if fill:
            attrs.append(f'android:fillColor="{fill}"')
        if stroke:
            attrs += [f'android:strokeColor="{stroke}"', f'android:strokeWidth="{f(width)}"', 'android:strokeLineCap="round"']
        if evenodd:
            attrs.append('android:fillType="evenOdd"')
        paths.append("    <path\n        " + "\n        ".join(attrs) + " />")
    return ('<?xml version="1.0" encoding="utf-8"?>\n'
            "<!-- Generated by tools/launcher_icon.py; edit the icon there, not here. -->\n"
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            '    android:width="108dp"\n    android:height="108dp"\n'
            '    android:viewportWidth="108"\n    android:viewportHeight="108">\n'
            + "\n".join(paths) + "\n</vector>\n")


def svg_group(ls, bg=None, mono=False):
    parts = [f'<rect width="108" height="108" fill="{bg}"/>'] if bg else []
    for d, fill, stroke, width, evenodd in ls:
        fill_value = "currentColor" if mono and fill else (fill or "none")
        stroke_value = "currentColor" if mono and stroke else stroke
        a = f'd="{d}" fill="{fill_value}"'
        if stroke_value:
            a += f' stroke="{stroke_value}" stroke-width="{f(width)}" stroke-linecap="round"'
        if evenodd:
            a += ' fill-rule="evenodd"'
        parts.append(f"<path {a}/>")
    return "".join(parts)


if __name__ == "__main__":
    what = sys.argv[1]
    if what == "foreground":
        print(vector_xml(layers(sys.argv[2])), end="")
    elif what == "monochrome":
        print(vector_xml(mono_layers()), end="")
    elif what == "svg-defs":
        for key in VARIANTS:
            print(f'<g id="ic-{key}">{svg_group(layers(key), bg=VARIANTS[key][1])}</g>')
        print(f'<g id="mono">{svg_group(mono_layers(), mono=True)}</g>')
